name: Make Json Files

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Render:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./phoenix-data
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --locked --all-extras   
      - name: Make json files
        run: uv run csv_to_json.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PHOENIX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PHOENIX_AWS_SECRET_ACCESS_KEY }}
